# Generated by Django 5.2.6 on 2025-11-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('intro', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mdl_forum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForumDiscussion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forum', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('userid', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'mdl_forum_discussions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discussion', models.IntegerField()),
                ('userid', models.IntegerField(null=True)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'mdl_forum_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('intro', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mdl_chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chatid', models.IntegerField()),
                ('userid', models.IntegerField(null=True)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'mdl_chat_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleContext',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contextlevel', models.IntegerField()),
                ('instanceid', models.IntegerField()),
            ],
            options={
                'db_table': 'mdl_context',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleCourse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('timecreated', models.BigIntegerField()),
                ('startdate', models.BigIntegerField()),
                ('visible', models.IntegerField()),
            ],
            options={
                'db_table': 'mdl_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleCourseModules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.IntegerField()),
                ('module', models.IntegerField()),
                ('instance', models.IntegerField()),
                ('section', models.IntegerField()),
            ],
            options={
                'db_table': 'mdl_course_modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleCourseSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.IntegerField()),
                ('section', models.IntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'mdl_course_sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleModules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mdl_modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mdl_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleRoleAssign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('contextid', models.IntegerField()),
                ('roleid', models.IntegerField()),
            ],
            options={
                'db_table': 'mdl_role_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('externalurl', models.TextField()),
            ],
            options={
                'db_table': 'mdl_url',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodleUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mdl_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_link', models.IntegerField()),
                ('safe_link', models.IntegerField()),
                ('suspicious', models.IntegerField()),
                ('malicious', models.IntegerField()),
                ('moodle_courseID', models.IntegerField()),
                ('moodle_courseName', models.CharField(max_length=200)),
                ('all_url', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('fullname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnsafeURL',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=350)),
                ('moodle_userID', models.IntegerField()),
                ('status', models.CharField(choices=[('malware', 'Malware'), ('phish', 'Phish'), ('adult', 'Adult'), ('suspicious', 'Suspicious')], max_length=10)),
                ('check_status', models.CharField(choices=[('safe', 'Safe'), ('not safe', 'Not Safe')], default='not safe', max_length=10)),
                ('source', models.CharField(max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsafe_urls', to='scraperSite.scanreport')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
